### ISSUE TITLE
problems with dataCleaning.ipynb

### ISSUE THREAD

**Issue by planeer** [krishnakartik1/LSTM-footballMatchWinner#2]
I have tried running through dataCleaning.ipynb and I am not getting quite the same end csv file as you did. And with my new csv there also isn't good prediction percentage in LSTM.ipynb. I also tried fixing what I thought was wrong with dataCleaning file, but no luck. Is there any chance you can share the original code you used for cleaning up the data, so you got such good end results?

**Comment by krishnakartik1** [comment]
Hey! I used only the codes on the repo itself. Did you go through fdManipulate.ipynb ? LSMTs don't perform well when there are characters in the data.

**Comment by planeer** [comment]
Well that's interesting. Yes I did, but when I went through everything, the produced csv file wasn't the same as yours.

**Comment by krishnakartik1** [comment]
Is it possible for you to pinpoint any particular cell that's causing this problem?
