### ISSUE TITLE
Dropped  seasons in "dataCleaning"

### ISSUE THREAD

**Issue by trendgiver111** [krishnakartik1/LSTM-footballMatchWinner#3]
There is something i do not quite understand. When you append last standings, you actually assign to "playing_statistics_4" and all others below "playing_statistics_3".
Shouldnt it be 3 to 3, 4 to 4, etc. ?

# playing_statistics_1 = get_last(playing_statistics_1, Standings, 0)
playing_statistics_2 = get_last(playing_statistics_2, Standings, "15")
playing_statistics_3 = get_last(playing_statistics_3, Standings, "14")
playing_statistics_4 = get_last(playing_statistics_3, Standings, "13")
playing_statistics_5 = get_last(playing_statistics_3, Standings, "12")
playing_statistics_6 = get_last(playing_statistics_3, Standings, "11")
playing_statistics_7 = get_last(playing_statistics_3, Standings, "10")
playing_statistics_8 = get_last(playing_statistics_3, Standings, "9")

**Comment by Cyki89** [comment]
@trendgiver111 
You are right. Of course, it is a big mistake in here. It cause that test and train set have almost identical data. This results in surprisingly good results.

**Comment by krishnakartik1** [comment]
Oh no. This does look fishy,  I'll look into this. Thanks for bringing it to my notice.
