### ISSUE TITLE
Incorrect approach in the new LSTM notebook

### ISSUE THREAD

**Issue by Suwadith** [krishnakartik1/LSTM-footballMatchWinner#5]
When creating training and test datasets you have used the following code

```
x_train, y_train = dataTrain.iloc[:,:28].values,dataTrain.iloc[:,28:].values
x_train=np.reshape(x_train,(1860,28,1))
x_test, y_test = dataTest.iloc[:,:28].values,dataTest.iloc[:,28:].values
x_test=np.reshape(x_test,(800,28,1))
```

`dataTrain.iloc[:,:28]` this is completely wrong. You are still passing the original FTR column(Which is actually the current match result), which is the 0th column. 

It should've been `dataTrain.iloc[:,1:28]` instead

The correct version would've been as described below
```
x_train, y_train = dataTrain.iloc[:,1:28].values,dataTrain.iloc[:,28:].values
x_train=np.reshape(x_train,(1860,27,1))
x_test, y_test = dataTest.iloc[:,1:28].values,dataTest.iloc[:,28:].values
x_test=np.reshape(x_test,(800,27,1))
```

When modified correctly it only gives 54% accuracy.

Hence the results produced are completely misleading.

**Comment by krishnakartik1** [comment]
Thanks for pointing it out, apologies for the oversight! I shall fix it
